# Generated by Django 4.1.4 on 2023-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('reciver_email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('mail_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
