# Generated by Django 4.1.4 on 2023-01-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecivedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived_subject', models.CharField(max_length=100)),
                ('recived_from', models.CharField(max_length=100)),
                ('recived_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
