# Generated by Django 4.1.4 on 2023-01-13 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0002_recivedinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinformation', to=settings.AUTH_USER_MODEL),
        ),
    ]
